# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Gifter' do
    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'
    use_frameworks!

    pod 'Alamofire', '~> 1.2'
    pod 'SwiftyJSON'
    pod 'SwiftValidator', '2.0.6'
end

target 'GifterTests' do

end

